### PR TITLE
added dish name

### PR DESCRIPTION
**Pull request by passionlord**
4th dish in the picture is called as enchiladas it's a Mexican cuisine 😊

### CODE REVIEW

**Review by Chetana16032002 — COMMENTED** [review]
well done!

**Comment by Chetana16032002** [comment]
what is the status now? is it still showing not participating?

**Comment by passionlord** [comment]
@Chetana16032002 it's working now

**Comment by Chetana16032002** [comment]
Cool.
@passionlord can you update the currently deployed website screenshots in the readme it still has lorem ipsum ones. this will be counted as new pull request

do partial screenshots shift+s+windows

**Comment by passionlord** [comment]
Sure

**Pull request merged**
