### PR TITLE
Added the cuisine names

### PR DESCRIPTION
**Pull request by NarayanBavisetti**

### CODE REVIEW

**Review by Chetana16032002 — COMMENTED** [review]
wow well done! @NarayanBavisetti

**Comment by NarayanBavisetti** [comment]
Its showing project not participating

**Comment by Chetana16032002** [comment]
@NarayanBavisetti  there seem to be having some conflicts in merging

**Comment by Chetana16032002** [comment]
image

**Comment by NarayanBavisetti** [comment]
can you check now

**Pull request merged**
